/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xchat_communication_Communication */

#ifndef _Included_com_xchat_communication_Communication
#define _Included_com_xchat_communication_Communication
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xchat_communication_Communication
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_xchat_communication_Communication_create
  (JNIEnv *, jobject);

/*
 * Class:     com_xchat_communication_Communication
 * Method:    registerOnHallDataCallback
 * Signature: (Lcom/xchat/communication/OnHallDataCallback;)V
 */
JNIEXPORT void JNICALL Java_com_xchat_communication_Communication_registerOnHallDataCallback
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_xchat_communication_Communication
 * Method:    registerOnRoomDataCallback
 * Signature: (Lcom/xchat/communication/OnRoomDataCallback;)V
 */
JNIEXPORT void JNICALL Java_com_xchat_communication_Communication_registerOnRoomDataCallback
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_xchat_communication_Communication
 * Method:    startHall
 * Signature: (Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_com_xchat_communication_Communication_startHall
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_xchat_communication_Communication
 * Method:    startRoom
 * Signature: (Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_com_xchat_communication_Communication_startRoom
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_xchat_communication_Communication
 * Method:    addMedia
 * Signature: (Ljava/lang/String;IILjava/lang/Object;Ljava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_com_xchat_communication_Communication_addMedia
  (JNIEnv *, jobject, jstring, jint, jint, jobject, jobject);

/*
 * Class:     com_xchat_communication_Communication
 * Method:    sendHallData
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_xchat_communication_Communication_sendHallData
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_xchat_communication_Communication
 * Method:    sendRoomData
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_xchat_communication_Communication_sendRoomData
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_xchat_communication_Communication
 * Method:    exit
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_xchat_communication_Communication_exit
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
